# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         GD-Arrow
version:      0.01
version_from: lib/GD/Arrow.pm
installdirs:  site
requires:
    Carp:                          0
    GD:                            0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
